management_system/managementApps/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views
app_name = 'managementApps'

urlpatterns = [
  
    path('login/', views.custom_login, name='custom_login'),
    
    path('home', views.site, name='create_site'),
    path('home/site', views.site, name="create_site"),
    path('home/site/update/<int:site_id>',views.update_site,name='update_site'),
    path('home/partner', views.partner, name="create_partner"),

    path('home/add-site',views.add_site,name="add_site"),
    path('home/add-partner',views.add_partner,name="add_partner"),
    path('home/partner/update/<int:partner_id>',views.update_partner,name='update_partner'),

    path('add_user/', views.add_user, name='add_user'),
    path('user_list', views.user_list, name='user_list'),
    path('update_user/<int:id>',views.update_user,name='update_user'),
    path('change_password/<int:id>',views.change_password,name='change_password'),
    path('logout/', views.logout_view, name='logout'),
   
 
]

management_system/management_system/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from managementApps import views

handler404 = 'managementApps.views.handler404'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.custom_login, name='custom_login'),
    path('app/', include('managementApps.urls')),
    
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

management_system/managementApps/models.py
from django.db import models

class Site(models.Model):
    site_id = models.AutoField(primary_key=True)
    sitename = models.CharField(max_length=100)
    sitekey = models.CharField(max_length=100)
    dns = models.CharField(max_length=16)
    company_name = models.CharField(max_length=100)
    country_name = models.CharField(max_length=100)


class Partner(models.Model):
    partner_id = models.AutoField(primary_key=True)
    partnername = models.CharField(max_length=100)
    partnerkey = models.CharField(max_length=100)
    dns = models.CharField(max_length=16)
    company_name = models.CharField(max_length=100)
    country_name = models.CharField(max_length=100)


    
class User(models.Model):
    username = models.CharField(max_length=100)
    email = models.EmailField()
    password = models.CharField(max_length=100)  # You should consider using a more secure way to store passwords.
    
    SUPERUSER_CHOICES = [
        ('yes', 'Yes'),
        ('no', 'No'),
    ]
    superuser = models.CharField(max_length=3, choices=SUPERUSER_CHOICES, default='no')
    
    READ_PERMISSION = 'read'
    WRITE_PERMISSION = 'write'
    
    PERMISSION_CHOICES = [
        (READ_PERMISSION, 'Read'),
        (WRITE_PERMISSION, 'Write'),
    ]
    permissions = models.CharField(max_length=255, choices=PERMISSION_CHOICES, default=READ_PERMISSION)

    def __str__(self):
        return self.username

management_system/managementApps/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from .models import Site, Partner, User
from rest_framework_jwt.settings import api_settings
from django.http import JsonResponse
import jwt
import datetime
from django.contrib.auth.hashers import check_password
from .decorators import token_required
from django.contrib.auth.hashers import make_password, check_password
from django.utils import timezone
from django.conf import settings
from decouple import config

SECRET_KEY = 'your-secret-key'


def root_page(request):
    return render(request, 'managementApps/auth/login.html')


@token_required
def home(request):
    return render(request, 'managementApps/base.html')


@token_required
def add_site(request):
    if request.session.get('username'):
        current_user = User.objects.filter(
            username=request.session.get('username')).first()
        if current_user and 'write' in current_user.permissions:
            return render(request, 'managementApps/content/add_site.html')
        else:
            return render(request, 'managementApps/error/401.html',  {'error': 'You are not allowed to add new site'})


@token_required
def site(request):
    message = ""
    username = request.session.get('username', '')
    current_user = User.objects.filter(
        username=request.session.get('username')).first()
    if request.method == 'POST':
        sitename = request.POST.get('sitename')
        sitekey = request.POST.get('sitekey')
        dns = request.POST.get('dns')
        company_name = request.POST.get('company_name')
        country_name = request.POST.get('country_name')
        site = Site(sitename=sitename, sitekey=sitekey, dns=dns,
                    company_name=company_name, country_name=country_name)

        if (sitename == "" or sitekey == "" or dns == "" or company_name == "" or country_name == ""):
            message = "Input Field Cannot be Empty!!"
        else:
            site.save()
            sites = Site.objects.all().order_by('site_id')
            message = "New Site Added Successfully"
            return render(request, 'managementApps/content/site.html', {'sites': sites, 'alert': message, 'username': username, 'user': current_user})

    sites = Site.objects.all().order_by('site_id')
    return render(request, 'managementApps/content/site.html', {'sites': sites, 'username': username, 'user': current_user})


@token_required
def update_site(request, site_id):
    site = get_object_or_404(Site, site_id=site_id)

    if request.session.get('username'):
        current_user = User.objects.filter(
            username=request.session.get('username')).first()
        if current_user and 'write' in current_user.permissions:
            if request.method == 'POST':
                # Retrieve the updated data from the request
                name = request.POST.get('sitename')
                sitekey = request.POST.get('sitekey')
                dns = request.POST.get('dns')
                company_name = request.POST.get('sitecompany')
                country_name = request.POST.get('sitecountry')
                # Update the site object with the new data
                site.sitename = name
                site.sitekey = sitekey
                site.dns = dns
                site.company_name = company_name
                site.country_name = country_name
                site.save()
                sites = Site.objects.all().order_by('site_id')
                message = "Site Updated Successfully"
                return render(request, 'managementApps/content/site.html', {'site': site, 'sites': sites, 'user': current_user, 'alert': message, })

            return render(request, 'managementApps/content/update_site.html', {'site': site})
        else:
            return render(request, 'managementApps/error/401.html',  {'error': 'You are not allowed to update site'})


@token_required
def partner(request):
    current_user = User.objects.filter(
        username=request.session.get('username')).first()
    if request.method == 'POST':
        partnername = request.POST.get('partnername')
        partnerkey = request.POST.get('partnerkey')
        dns = request.POST.get('dns')
        company_name = request.POST.get('company_name')
        country_name = request.POST.get('country_name')
        partner = Partner(partnername=partnername, partnerkey=partnerkey,
                          dns=dns, company_name=company_name, country_name=country_name)

        if (partnername == "" or partnerkey == "" or dns == "" or company_name == "" or country_name == ""):
            alertMessage = "Input Field Cannot be Empty!!"
        else:
            partner.save()
            partners = Partner.objects.all().order_by('partner_id')
            message = "Partner Added Successfully"
            return render(request, 'managementApps/content/partner.html', {'partners': partners, 'alert': message, 'user': current_user})

    partners = Partner.objects.all().order_by('partner_id')
    return render(request, 'managementApps/content/partner.html', {'partners': partners, 'user': current_user})


@token_required
def add_partner(request):
    if request.session.get('username'):
        current_user = User.objects.filter(
            username=request.session.get('username')).first()
        if current_user and 'write' in current_user.permissions:
            return render(request, 'managementApps/content/add_partner.html')
        else:
            return render(request, 'managementApps/error/401.html',  
                          {'error': 'You are not allowed to add new partner'})


@token_required
def update_partner(request, partner_id):
    partner = get_object_or_404(Partner, partner_id=partner_id)
    if request.session.get('username'):
        current_user = User.objects.filter(
            username=request.session.get('username')).first()
        if current_user and 'write' in current_user.permissions:
            if request.method == 'POST':
                # Retrieve the updated data from the request
                name = request.POST.get('partnername')
                partnerkey = request.POST.get('partnerkey')
                dns = request.POST.get('dns')
                company_name = request.POST.get('partnercompany')
                country_name = request.POST.get('partnercountry')
                # Update the site object with the new data
                partner.partnername = name
                partner.partnerkey = partnerkey
                partner.dns = dns
                partner.company_name = company_name
                partner.country_name = country_name
                partner.save()
                partners = Partner.objects.all().order_by('partner_id')
                message = "Partner Updated Successfully"
                return render(request, 'managementApps/content/partner.html', {'partner': site, 'partners': partners, 'user': current_user, 'alert': message})

            return render(request, 'managementApps/content/update_partner.html', {'partner': partner, 'user': current_user})
        else:
            return render(request, 'managementApps/error/401.html',  {'error': 'You are not allowed to update partner'})


@token_required
def add_user(request):
    if request.method == 'POST':
        # Check if the user making the request is a superuser
        if request.session.get('username'):
            current_user = User.objects.filter(
                username=request.session.get('username')).first()
            if current_user and current_user.superuser == 'yes':
                # Retrieve form data
                username = request.POST.get('username')
                email = request.POST.get('email')
                password = request.POST.get('password')
                superuser = request.POST.get('superuser')
                permissions = request.POST.getlist('permissions')

                if permissions == []:
                    permissions = ['read']

                # Check if the username already exists
                existing_user = User.objects.filter(username=username).first()
                if existing_user:
                    return render(request, 'managementApps/auth/add_user.html', {'error': 'Username already exists'})

                # Create and save the user
                user = User(username=username, email=email, password=make_password(password),
                            superuser=superuser, permissions=','.join(permissions))
                user.save()

                users = User.objects.all().order_by('id')
                message = "New User Created Successfully"
                # Redirect to a page showing the user list or any other appropriate view
                return render(request, 'managementApps/auth/user_list.html', {'users': users, 'alert': message})

        # If the user is not a superuser or not logged in, handle accordingly
        return render(request, 'managementApps/error/401.html', {'error': 'You are not allowed to create a user'})
    else:
        if request.session.get('username'):
            current_user = User.objects.filter(
                username=request.session.get('username')).first()
            if current_user and current_user.superuser == 'yes':
                return render(request, 'managementApps/auth/add_user.html')
            else:
                return render(request, 'managementApps/error/401.html',  {'error': 'You are not allowed to create a user'})


def custom_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        try:
            user = User.objects.filter(username=username).first()
        except User.DoesNotExist:
            return JsonResponse({'error': 'Invalid credentials'}, status=400)

        if user and check_password(password, user.password):

management_system/managementApps/templates/managementApps/partials/alert.html
{% if alert %}
<div class="alert-container d-flex justify-content-center align-items-center">
    <div id="auto-hide-alert" class="alert alert-success alert-dismissible fade show"
        style="position: fixed; z-index: 100;" role="alert">
        <strong>{{ alert }}</strong> 
    </div>
</div>
{% endif %}

management_system/managementApps/templates/managementApps/partials/dropdown.html
{% load custom_filters %}

<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown"
    aria-expanded="false">
    {% get_username request as username %}
    {% if username %}
    <span class="fs-5"><i class="fa-solid fa-user"></i> {{ username }}</span>
    {% endif %}

  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li><a class="dropdown-item" href="{% url 'managementApps:add_user' %}">Add User</a></li>
    <li><a class="dropdown-item" href="{% url 'managementApps:user_list' %}">Users List</a></li>
    <li>
      <hr class="dropdown-divider">
    </li>
    <li><a class="dropdown-item text-danger" href="/app/logout">Logout</a></li>
  </ul>
</div>

management_system/managementApps/templates/managementApps/partials/footer.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script
src="https://code.jquery.com/jquery-3.6.0.min.js"
integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
crossorigin="anonymous"
></script>
<script
src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
crossorigin="anonymous"
></script>
<script src="{% static 'managementApps/js/script.js' %}"></script>
</body>
</html>

management_system/managementApps/templates/managementApps/partials/header.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" type="text/css" href="{% static 'managementApps/css/styles.css' %}">
    <title>Management System</title>
</head>

<body>

management_system/managementApps/templates/managementApps/partials/nav.html
{% load custom_filters %}

<div class="container-nav">
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow">
        <div class="d-flex justify-content-between w-100 container-lg">
            <div class="d-flex align-items-center">
                {% get_username request as username %}
                {% if username %}
                <a class="navbar-brand" href="{% url 'managementApps:create_site' %}">
                    {% else %}
                    <a class="navbar-brand" href="{% url 'managementApps:custom_login' %}">
                        {% endif %}

                        <span class="text-dark title">Management</span><span class="text-danger title"> System</span>
                    </a>
            </div>
            <div class="d-flex align-items-center">
                <!-- Form for large devices -->
                <form class="form-inline d-none d-lg-block" method="get" action="#">
                    <div class="input-group">
                        <input class="form-control" type="search" placeholder="Search ..." aria-label="Search"
                            name="query" required>
                        <button type="submit" class="btn btn-warning">Search</button>
                    </div>
                </form>
            </div>

            {% get_username request as username %}
            {% if username %}
            {% include 'managementApps/partials/dropdown.html' %}
            {% endif %}

        </div>

    </nav>
    <!-- Form for medium and small devices -->
    <form class="form-inline d-block d-lg-none mt-2" method="get" action="#">
        <div class="input-group">
            <input class="form-control" type="search" placeholder="Search ..." aria-label="Search" name="query"
                required>
            <button type="submit" class="btn btn-warning">Search</button>
        </div>
    </form>
</div>

management_system/managementApps/templates/managementApps/partials/sidenav.html
<div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
    <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
        <a href="#" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
            <span class="fs-5 d-none d-sm-inline">Menu</span>
        </a>
        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
            <li class="nav-item">
                <a href="/app/home/site" class="nav-link align-middle px-0">
                    <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline text-light">Site</span>
                </a>
            </li>
            <li>
                <a href="/app/home/partner" class="nav-link px-0 align-middle">
                    <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline text-light">Partner</span></a>
            </li>
            <hr>

        </ul>

    </div>
</div>