management_system/managementApps/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views
app_name = 'managementApps'

urlpatterns = [
  
    path('login/', views.custom_login, name='custom_login'),
    
    path('home', views.site, name='create_site'),
    path('home/site', views.site, name="create_site"),
    path('home/site/update/<int:site_id>',views.update_site,name='update_site'),
    path('home/partner', views.partner, name="create_partner"),

    path('home/add-site',views.add_site,name="add_site"),
    path('home/add-partner',views.add_partner,name="add_partner"),
    path('home/partner/update/<int:partner_id>',views.update_partner,name='update_partner'),

    path('add_user/', views.add_user, name='add_user'),
    path('user_list', views.user_list, name='user_list'),
    path('update_user/<int:id>',views.update_user,name='update_user'),
    path('change_password/<int:id>',views.change_password,name='change_password'),
    path('logout/', views.logout_view, name='logout'),
   
 
]

management_system/management_system/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from managementApps import views

handler404 = 'managementApps.views.handler404'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.custom_login, name='custom_login'),
    path('app/', include('managementApps.urls')),
    
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

management_system/managementApps/models.py
from django.db import models

class Site(models.Model):
    site_id = models.AutoField(primary_key=True)
    sitename = models.CharField(max_length=100)
    sitekey = models.CharField(max_length=100)
    dns = models.CharField(max_length=16)
    company_name = models.CharField(max_length=100)
    country_name = models.CharField(max_length=100)


class Partner(models.Model):
    partner_id = models.AutoField(primary_key=True)
    partnername = models.CharField(max_length=100)
    partnerkey = models.CharField(max_length=100)
    dns = models.CharField(max_length=16)
    company_name = models.CharField(max_length=100)
    country_name = models.CharField(max_length=100)


    
class User(models.Model):
    username = models.CharField(max_length=100)
    email = models.EmailField()
    password = models.CharField(max_length=100)  # You should consider using a more secure way to store passwords.
    
    SUPERUSER_CHOICES = [
        ('yes', 'Yes'),
        ('no', 'No'),
    ]
    superuser = models.CharField(max_length=3, choices=SUPERUSER_CHOICES, default='no')
    
    READ_PERMISSION = 'read'
    WRITE_PERMISSION = 'write'
    
    PERMISSION_CHOICES = [
        (READ_PERMISSION, 'Read'),
        (WRITE_PERMISSION, 'Write'),
    ]
    permissions = models.CharField(max_length=255, choices=PERMISSION_CHOICES, default=READ_PERMISSION)

    def __str__(self):
        return self.username

management_system/managementApps/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from .models import Site, Partner, User
from rest_framework_jwt.settings import api_settings
from django.http import JsonResponse
import jwt
import datetime
from django.contrib.auth.hashers import check_password
from .decorators import token_required
from django.contrib.auth.hashers import make_password, check_password
from django.utils import timezone
from django.conf import settings
from decouple import config

SECRET_KEY = 'your-secret-key'


def root_page(request):
    return render(request, 'managementApps/auth/login.html')


@token_required
def home(request):
    return render(request, 'managementApps/base.html')


@token_required
def add_site(request):
    if request.session.get('username'):
        current_user = User.objects.filter(
            username=request.session.get('username')).first()
        if current_user and 'write' in current_user.permissions:
            return render(request, 'managementApps/content/add_site.html')
        else:
            return render(request, 'managementApps/error/401.html',  {'error': 'You are not allowed to add new site'})


@token_required
def site(request):
    message = ""
    username = request.session.get('username', '')
    current_user = User.objects.filter(
        username=request.session.get('username')).first()
    if request.method == 'POST':
        sitename = request.POST.get('sitename')
        sitekey = request.POST.get('sitekey')
        dns = request.POST.get('dns')
        company_name = request.POST.get('company_name')
        country_name = request.POST.get('country_name')
        site = Site(sitename=sitename, sitekey=sitekey, dns=dns,
                    company_name=company_name, country_name=country_name)

        if (sitename == "" or sitekey == "" or dns == "" or company_name == "" or country_name == ""):
            message = "Input Field Cannot be Empty!!"
        else:
            site.save()
            sites = Site.objects.all().order_by('site_id')
            message = "New Site Added Successfully"
            return render(request, 'managementApps/content/site.html', {'sites': sites, 'alert': message, 'username': username, 'user': current_user})

    sites = Site.objects.all().order_by('site_id')
    return render(request, 'managementApps/content/site.html', {'sites': sites, 'username': username, 'user': current_user})


@token_required
def update_site(request, site_id):
    site = get_object_or_404(Site, site_id=site_id)

    if request.session.get('username'):
        current_user = User.objects.filter(
            username=request.session.get('username')).first()
        if current_user and 'write' in current_user.permissions:
            if request.method == 'POST':
                # Retrieve the updated data from the request
                name = request.POST.get('sitename')
                sitekey = request.POST.get('sitekey')
                dns = request.POST.get('dns')
                company_name = request.POST.get('sitecompany')
                country_name = request.POST.get('sitecountry')
                # Update the site object with the new data
                site.sitename = name
                site.sitekey = sitekey
                site.dns = dns
                site.company_name = company_name
                site.country_name = country_name
                site.save()
                sites = Site.objects.all().order_by('site_id')
                message = "Site Updated Successfully"
                return render(request, 'managementApps/content/site.html', {'site': site, 'sites': sites, 'user': current_user, 'alert': message, })

            return render(request, 'managementApps/content/update_site.html', {'site': site})
        else:
            return render(request, 'managementApps/error/401.html',  {'error': 'You are not allowed to update site'})


@token_required
def partner(request):
    current_user = User.objects.filter(
        username=request.session.get('username')).first()
    if request.method == 'POST':
        partnername = request.POST.get('partnername')
        partnerkey = request.POST.get('partnerkey')
        dns = request.POST.get('dns')
        company_name = request.POST.get('company_name')
        country_name = request.POST.get('country_name')
        partner = Partner(partnername=partnername, partnerkey=partnerkey,
                          dns=dns, company_name=company_name, country_name=country_name)

        if (partnername == "" or partnerkey == "" or dns == "" or company_name == "" or country_name == ""):
            alertMessage = "Input Field Cannot be Empty!!"
        else:
            partner.save()
            partners = Partner.objects.all().order_by('partner_id')
            message = "Partner Added Successfully"
            return render(request, 'managementApps/content/partner.html', {'partners': partners, 'alert': message, 'user': current_user})

    partners = Partner.objects.all().order_by('partner_id')
    return render(request, 'managementApps/content/partner.html', {'partners': partners, 'user': current_user})


@token_required
def add_partner(request):
    if request.session.get('username'):
        current_user = User.objects.filter(
            username=request.session.get('username')).first()
        if current_user and 'write' in current_user.permissions:
            return render(request, 'managementApps/content/add_partner.html')
        else:
            return render(request, 'managementApps/error/401.html',  
                          {'error': 'You are not allowed to add new partner'})


@token_required
def update_partner(request, partner_id):
    partner = get_object_or_404(Partner, partner_id=partner_id)
    if request.session.get('username'):
        current_user = User.objects.filter(
            username=request.session.get('username')).first()
        if current_user and 'write' in current_user.permissions:
            if request.method == 'POST':
                # Retrieve the updated data from the request
                name = request.POST.get('partnername')
                partnerkey = request.POST.get('partnerkey')
                dns = request.POST.get('dns')
                company_name = request.POST.get('partnercompany')
                country_name = request.POST.get('partnercountry')
                # Update the site object with the new data
                partner.partnername = name
                partner.partnerkey = partnerkey
                partner.dns = dns
                partner.company_name = company_name
                partner.country_name = country_name
                partner.save()
                partners = Partner.objects.all().order_by('partner_id')
                message = "Partner Updated Successfully"
                return render(request, 'managementApps/content/partner.html', {'partner': site, 'partners': partners, 'user': current_user, 'alert': message})

            return render(request, 'managementApps/content/update_partner.html', {'partner': partner, 'user': current_user})
        else:
            return render(request, 'managementApps/error/401.html',  {'error': 'You are not allowed to update partner'})


@token_required
def add_user(request):
    if request.method == 'POST':
        # Check if the user making the request is a superuser
        if request.session.get('username'):
            current_user = User.objects.filter(
                username=request.session.get('username')).first()
            if current_user and current_user.superuser == 'yes':
                # Retrieve form data
                username = request.POST.get('username')
                email = request.POST.get('email')
                password = request.POST.get('password')
                superuser = request.POST.get('superuser')
                permissions = request.POST.getlist('permissions')

                if permissions == []:
                    permissions = ['read']

                # Check if the username already exists
                existing_user = User.objects.filter(username=username).first()
                if existing_user:
                    return render(request, 'managementApps/auth/add_user.html', {'error': 'Username already exists'})

                # Create and save the user
                user = User(username=username, email=email, password=make_password(password),
                            superuser=superuser, permissions=','.join(permissions))
                user.save()

                users = User.objects.all().order_by('id')
                message = "New User Created Successfully"
                # Redirect to a page showing the user list or any other appropriate view
                return render(request, 'managementApps/auth/user_list.html', {'users': users, 'alert': message})

        # If the user is not a superuser or not logged in, handle accordingly
        return render(request, 'managementApps/error/401.html', {'error': 'You are not allowed to create a user'})
    else:
        if request.session.get('username'):
            current_user = User.objects.filter(
                username=request.session.get('username')).first()
            if current_user and current_user.superuser == 'yes':
                return render(request, 'managementApps/auth/add_user.html')
            else:
                return render(request, 'managementApps/error/401.html',  {'error': 'You are not allowed to create a user'})


def custom_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        try:
            user = User.objects.filter(username=username).first()
        except User.DoesNotExist:
            return JsonResponse({'error': 'Invalid credentials'}, status=400)

        if user and check_password(password, user.password):

management_system/managementApps/templates/managementApps/content/add_partner.html
{% include 'managementApps/partials/header.html' %}

{% include 'managementApps/partials/nav.html' %}


<div class="container">
  <div class="card">
    <div class="card-body">
        <h5 class="card-title text-center text-danger">Add Partner</h5>
        <form action="{% url 'managementApps:create_partner' %}" method="post" id="partnerForm">
            {% csrf_token %}
        
            <div class="row">
                <div class="col">
                  <label for="partnername">Partner Name</label>
                <input type="text" class="form-control mt-2" name="partnername" id="partner-name"  required>
                
                <div class="col">
                  <label for="partnerkey">Partner Key</label>
                <input type="text" class="form-control mt-2" name="partnerkey" required>
      
                </div>
                </div>
              </div>
              <div class="row">
                <div class="col">
                  <label for="dns">DNS</label>
                <input type="text" class="form-control mt-2" name="dns"  required>
                </div>
                <div class="col">
                  <label for="company_name">Company Name</label>
                <input type="text" class="form-control mt-2" name="company_name"  required>
                </div>
              </div>
      
              <div class="row">
                <div class="col">
                  <label for="country_name">Country Name</label>
                  <input type="text" class="form-control mt-2" name="country_name"  required>
                </div>
              </div>

            <input type=button class="btn btn-primary mt-3" value="Back" onClick="javascript:history.go(-1);">
            <button type="submit" class="btn btn-primary mt-3 text-center">Save</button>
          </form>
    </div>
  </div>
  </div>

  {% include 'managementApps/partials/footer.html' %}

management_system/managementApps/templates/managementApps/content/add_site.html
{% include 'managementApps/partials/header.html' %}

{% include 'managementApps/partials/nav.html' %}


<div class="container">
  <div class="card">
    <div class="card-body">
        <h5 class="card-title text-center text-danger">Add Site</h5>
        <form action="{% url 'managementApps:create_site' %}" method="post" id="siteForm">
            {% csrf_token %}
        
            <div class="row">
                <div class="col">
                  <label for="sitename">Site Name</label>
                <input type="text" class="form-control mt-2" name="sitename" id="site-name"  required>
                
                <div class="col">
                  <label for="sitekey">Site Key</label>
                <input type="text" class="form-control mt-2" name="sitekey" required>
      
                </div>
                </div>
              </div>
              <div class="row">
                <div class="col">
                  <label for="dns">DNS</label>
                <input type="text" class="form-control mt-2" name="dns"  required>
                </div>
                <div class="col">
                  <label for="company_name">Company Name</label>
                <input type="text" class="form-control mt-2" name="company_name"  required>
                </div>
              </div>
      
              <div class="row">
                <div class="col">
                  <label for="country_name">Country Name</label>
                  <input type="text" class="form-control mt-2" name="country_name"  required>
                </div>
              </div>

            <input type=button class="btn btn-primary mt-3" value="Back" onClick="javascript:history.go(-1);">
            <button type="submit" class="btn btn-primary mt-3 text-center">Save</button>
          </form>
    </div>
  </div>
  </div>

  {% include 'managementApps/partials/footer.html' %}

management_system/managementApps/templates/managementApps/content/partner.html
{% include 'managementApps/partials/header.html' %}

{% include 'managementApps/partials/nav.html' %}

{% include 'managementApps/partials/alert.html' %}

<div class="container-fluid">
  <div class="row flex-nowrap">

    {% include 'managementApps/partials/sidenav.html' %}

    <div class="col py-3">
      <div class="text-center mt-2">
        {% include 'managementApps/partials/alert.html' %}
        <span class="h3">Partner Config</span>
        <hr>
        <a href="/app/home/add-partner" class="float-end btn btn-primary me-3"> + Add
          Partner</a>
      </div>
      <table class="table table-striped table-hover">
        <thead>
          <tr class="text-center">
            <th scope="col">Serial</th>
            <th scope="col">Partner Name</th>
            <th scope="col">Partner Key</th>
            <th scope="col">DNS</th>
            <th scope="col">Company</th>
            <th scope="col">Country</th>
            {% if 'write' in user.permissions %}
            <th scope="col">Update</th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
          {% for partner in partners %}
          <tr class="text-center">
            <th scope="row">{{partner.partner_id}}</th>
            <td>{{partner.partnername}}</td>
            <td>{{partner.partnerkey}}</td>
            <td>{{partner.dns}}</td>
            <td>{{partner.company_name}}</td>
            <td>{{partner.country_name}}</td>
            {% if 'write' in user.permissions %}
              <td> <a href="/app/home/partner/update/{{partner.partner_id}}" class="update-partner btn btn-dark">Update</a></td>
              {% endif %}


          </tr>
         {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>





{% include 'managementApps/partials/footer.html' %}

management_system/managementApps/templates/managementApps/content/site.html
{% include 'managementApps/partials/header.html' %}

{% include 'managementApps/partials/nav.html' %}

{% include 'managementApps/partials/alert.html' %}

<div class="container-fluid">
  <div class="row flex-nowrap">

    {% include 'managementApps/partials/sidenav.html' %}

    <div class="col py-3">
      <div class="text-center mt-2">
        <span class="h3">Site Config</span>
        <hr>
        <a href="/app/home/add-site" class="float-end btn btn-primary me-3"> + Add
          Site</a>
      </div>
      <table class="table table-striped">
        <thead>
          <tr class="text-center">
            <th scope="col">Serial</th>
            <th scope="col">Site Name</th>
            <th scope="col">Site Key</th>
            <th scope="col">DNS</th>
            <th scope="col">Company</th>
            <th scope="col">Country</th>
            {% if 'write' in user.permissions %}
            <th scope="col">Update</th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
          {% for site in sites %}
          <tr class="text-center">
            <th scope="row">{{site.site_id}}</th>
            <td>{{site.sitename}}</td>
            <td>{{site.sitekey}}</td>
            <td>{{site.dns}}</td>
            <td>{{site.company_name}}</td>
            <td>{{site.country_name}}</td>
            {% if 'write' in user.permissions %}
            <td> <a href="/app/home/site/update/{{site.site_id}}" class="update-site btn btn-dark">Update</a></td>
            {% endif %}
         {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>


{% include 'managementApps/partials/footer.html' %}

management_system/managementApps/templates/managementApps/content/update_partner.html
{% include 'managementApps/partials/header.html' %}

{% include 'managementApps/partials/nav.html' %}


<div class="container">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title text-center text-danger">Update Partner</h5>
      <form action="{% url 'managementApps:update_partner' partner.partner_id %}" method="post" id="partnerForm">
        {% csrf_token %}

        <div class="row">
          <div class="col-12">

            <label for="partnername">Partner Name</label>
            <input type="text" class="form-control bg-secondary text-light" name="partnername" id="partner-name" value="{{ partner.partnername }}" readonly>

          </div>

          <div class="col-12">

            <label for="partnerkey">Partner Key</label>
            <input type="text" class="form-control" name="partnerkey" value="{{ partner.partnerkey }}" required>

          </div>
        </div>
        <div class="row">
          <div class="col">

            <label for="partnerdns">DNS</label>
            <input type="text" class="form-control" name="dns" id="partner-dns" value="{{ partner.dns}}" required>

          </div>

          <div class="col">

            <label for="partnercompany">Partner Key</label>
            <input type="text" class="form-control" name="partnercompany" value="{{ partner.company_name }}" required>

          </div>
        </div>

        <div class="row">
          <div class="col">

            <label for="partnercountry">Partner Name</label>
            <input type="text" class="form-control" name="partnercountry" id="partner-country" value="{{ partner.country_name }}"
              required>

          </div>
        </div>
        <input type=button class="btn btn-primary mt-3" value="Back" onClick="javascript:history.go(-1);">
        <button type="submit" class="btn btn-primary mt-3 text-center">Save</button>
      </form>
    </div>
  </div>
</div>

{% include 'managementApps/partials/footer.html' %}

management_system/managementApps/templates/managementApps/content/update_site.html
{% include 'managementApps/partials/header.html' %}

{% include 'managementApps/partials/nav.html' %}


<div class="container">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title text-center text-danger">Update Site</h5>
      <form action="{% url 'managementApps:update_site' site.site_id %}" method="post" id="siteForm">
        {% csrf_token %}

        <div class="row">
          <div class="col-12">

            <label for="sitename">Site Name</label>
            <input type="text" class="form-control bg-secondary text-light" name="sitename" id="site-name" value="{{ site.sitename }}" readonly>

          </div>

          <div class="col-12">

            <label for="sitekey">Site Key</label>
            <input type="text" class="form-control" name="sitekey" value="{{ site.sitekey }}" required>

          </div>
        </div>
        <div class="row">
          <div class="col">

            <label for="sitedns">DNS</label>
            <input type="text" class="form-control" name="dns" id="site-dns" value="{{ site.dns}}" required>

          </div>

          <div class="col">

            <label for="sitecompany">Site Key</label>
            <input type="text" class="form-control" name="sitecompany" value="{{ site.company_name }}" required>

          </div>
        </div>

        <div class="row">
          <div class="col">

            <label for="sitecountry">Site Name</label>
            <input type="text" class="form-control" name="sitecountry" id="site-country" value="{{ site.country_name }}"
              required>

          </div>
        </div>
        <input type=button class="btn btn-primary mt-3" value="Back" onClick="javascript:history.go(-1);">
        <button type="submit" class="btn btn-primary mt-3 text-center">Save</button>
      </form>
    </div>
  </div>
</div>

{% include 'managementApps/partials/footer.html' %}